#name: docker-push
#
#on:
#  push:
#    branches:
#      - main
#      - cad-all
#  pull_request:
#    types: [ opened, reopened ]
#  release:
#    types: [ published ]
#
## Build and push the Docker image
#jobs:
#  push_to_registry:
#    name: Build and push Docker image to Docker Hub
#    runs-on: ubuntu-latest
#    steps:
#      - name: Git config
#        run: |
#          git config --global init.defaultBranch main
#      - name: Check out the repo
#        uses: actions/checkout@v2
#      - name: Build and push image to the Docker Hub
#        uses: docker/build-push-action@v2
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_PASSWORD }}
#          repository: ${{ secrets.DOCKERHUB_REPOSITORY }}
#          tag_with_ref: true
#          tag_with_sha: true
#          tags: latest

name: docker-push

on:
  push:
    branches:
      - main
      - cad-all

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}