name: docker-push

on:
  workflow_dispatch:
    workflows: [ "Build" ]
  pull_request:
    types: [ opened, reopened ]
  release:
    types: [ published ]

  # Build and push the Docker image
jobs:
  push_to_registry:
    name: Build and push Docker image to Docker Hub
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build and push image to the Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ secrets.DOCKERHUB_REPOSITORY }}
          tag_with_ref: true
          tag_with_sha: true
          tags: latest